### ISSUE TITLE
Hi, problem about solving your example

### ISSUE THREAD

**Issue by sbabadag** [BriefFiniteElementNet/BFE.Net.devdocs#1]
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BriefFiniteElementNet;
using BriefFiniteElementNet.Common;
using BriefFiniteElementNet.Controls;
using BriefFiniteElementNet.Elements;
using BriefFiniteElementNet.Loads;
using BriefFiniteElementNet.Materials;
using BriefFiniteElementNet.Sections;
using BriefFiniteElementNet.Solver;

namespace Portique

{

    public struct TNPoint
    {
        public TNPoint(double x,double y,double z)
        {
            X = x;
            Y = y;
            Z = z;
        }
        public double X, Y, Z;
    }

    public struct TForces
    {
        public TForces(string Fno,double St,double a, double b, double c, double d, double e, double f)
        {
            fx = a;
            fy = b;
            fz = c;
            mx = d;
            my = e;
            mz = f;
            fno = Fno;
            st = St;
        }
        public double fx, fy, fz;
        public double mx, my, mz;
        public string fno;
        public double st;
    }

    public struct Profiles
    {
        public Profiles(string Name, double H, double B, double T, double S, double W, double Wx, double Wy, double A, double IX)
        {
            name = Name;
            h = H;
            b = B;
            t = T;
            s = S;
            w = W;
            wx = Wx;
            wy = Wy;
            a = A;
            Ix = IX;
        }

        public string name;
        public double t;
        public double s;
        public double h;
        public double b;
        public double w;
        public double wx;
        public double wy;
        public double a;
        public double Ix;
    }

    public class BFEclasses
    {
        private Model model;
        private LoadCombination D_combination;
        private LoadCombination D_L_combination;
        private LoadCombination D_WX_combination;
        private LoadCombination D_WY_combination;
        private LoadCombination D_QX_combination;
        private LoadCombination D_QY_combination;
        private ProfileClass    Profiles;
        private int nodeCount;
        private int frameCount;
        private LoadCase lc_dead;
        private LoadCase lc_live;
        private LoadCase lc_snow;
        private LoadCase lc_wind;
        private LoadCase lc_quake;
        private List<TForces> tmp;

        public BFEclasses()
         {
            model = new Model();
            Profiles = new ProfileClass();
            nodeCount = 0;
            frameCount = 0;
            tmp = new List<TForces>();

            // Load cases and combinations
             lc_dead  = new LoadCase("dead",  LoadType.Dead);
             lc_live  = new LoadCase("live",  LoadType.Live);
             lc_snow  = new LoadCase("snow",  LoadType.Snow);
             lc_wind  = new LoadCase("wind",  LoadType.Wind);
             lc_quake = new LoadCase("quake", LoadType.Quake);

            D_combination       = new LoadCombination();
            D_L_combination     = new LoadCombination();
            D_WX_combination    = new LoadCombination();
            D_WY_combination    = new LoadCombination();
            D_QX_combination    = new LoadCombination();
            D_QY_combination    = new LoadCombination();

            D_combination[lc_dead] = 1;

            D_L_combination[lc_dead] = 1;
            D_L_combination[lc_snow] = 1;

            D_WX_combination[lc_dead] = 1;
            D_WX_combination[lc_snow] = 1;
            D_WX_combination[lc_wind] = 1;

            D_WY_combination[lc_dead] = 1;
            D_WY_combination[lc_snow] = 1;
            D_WY_combination[lc_wind] = 1;

            D_QX_combination[lc_dead] = 1;
            D_QX_combination[lc_snow] = 1;
            D_QX_combination[lc_quake]= 1;

            D_QY_combination[lc_dead] = 1;
            D_QY_combination[lc_snow] = 1;
            D_QY_combination[lc_quake]= 1;

            // end of load cases and combinations

        }

        public void addLoadtoFrame(string f, string the_case,char loadDirection,float magnitude)
        {
             BarElement el = new BarElement();
             LoadCase c = lc_dead;

            

            foreach (BarElement e in model.Elements) { if (e.Label == f) { el = e;} }

            switch (the_case)
            {
                case "dead": { c = lc_dead; break; }
                case "live": { c = lc_live; break; }
                case "snow": { c = lc_snow; break; }
                case "wind": { c = lc_wind; break; }
                case "quake":{ c = lc_quake; break; }
            }

            

            switch (loadDirection) {
                case 'x': {
                        el.Loads.Add(new UniformLoad(c, Vector.I, magnitude, CoordinationSystem.Local));
                        break; }
                case 'y': {
                        el.Loads.Add(new UniformLoad(c, Vector.J, magnitude, CoordinationSystem.Local));
                        break; }                        
                case 'z': {                             
                        el.Loads.Add(new UniformLoad(c, Vector.K, magnitude, CoordinationSystem.Local));
                        break; }                        
                case 'X': {                            
                        el.Loads.Add(new UniformLoad(c, Vector.I, magnitude, CoordinationSystem.Global));
                        break; }                        
                case 'Y': {                            
                        el.Loads.Add(new UniformLoad(c, Vector.J, magnitude, CoordinationSystem.Global));
                        break; }                        
                case 'Z': {                             
                        el.Loads.Add(new UniformLoad(c, Vector.K, magnitude, CoordinationSystem.Global));
                        break; }
            }

        }
        public void setRestraint(string label,string r)
        {
            model.Nodes[label].Constraints = restraint(r);
        }

        public void analyse()
        {

            model.Solve();
        //    WpfTraceListener wnd = WpfTraceListener.CreateModelTrace(model);
        //    new BriefFiniteElementNet.ModelWarningChecker().CheckModel(model);
        //    wnd.ShowDialog();

        }
        public List<TForces> getResults(int comb)
        {
             
            LoadCombination LC = new LoadCombination();

            switch (comb)
            {
                case 1: { LC = D_combination; break; }
                case 2: { LC = D_L_combination; break; }
                case 3: { LC = D_WX_combination ; break;}
                case 4: { LC = D_WY_combination; break; }
                case 5: { LC = D_QX_combination; break; }
                case 6: { LC = D_QY_combination; break; }
                default: { LC = D_combination; break; }
            }

            foreach (BarElement e in model.Elements)
            {
                var l = e.GetElementLength();
                for (double i = 0; i < 1; i+=0.01)
                {
                    Force r = e.GetExactInternalForceAt(i,LC);
                    tmp.Add(new TForces(e.Label,Math.Round(i*l,2), Math.Round(r.Fx,0), Math.Round(r.Fy,0), Math.Round(r.Fz,0), Math.Round(r.Mx,0), Math.Round(r.My,0), Math.Round(r.Mz,0)));
                }

                
            }

            return tmp;
        }

        public string addFrame(TNPoint I, TNPoint J, string section, string r1, string r2)
        {
            Node n1, n2;
            frameCount++;

            if (nodeExists(I) != null) { n1 = nodeExists(I); } else { n1 = new Node(I.X, I.Y, I.Z); nodeCount++; n1.Label = Convert.ToString(nodeCount); model.Nodes.Add(n1); }

            if (nodeExists(J) != null) { n2 = nodeExists(J); } else { n2 = new Node(J.X, J.Y, J.Z); nodeCount++; n2.Label = Convert.ToString(nodeCount); model.Nodes.Add(n2);
            }

            var e = new BarElement(n1, n2) { Label = "frame " + Convert.ToString(frameCount)};

            var mat = UniformIsotropicMaterial.CreateFromYoungPoisson(210e9, 0.3);
            var P = Profiles.findProfile(section);
            var sec = new BriefFiniteElementNet.Sections.UniformGeometric1DSection(SectionGenerator.GetISetion(P.b / 1000, P.h / 1000, P.t / 1000, P.s / 1000));
            e.Section = sec;
            e.Material = mat;
            // e.UseOverridedProperties = false;

            //   e.StartReleaseCondition = Constraints.FixedDY;
            //   e.EndReleaseCondition = Constraints.FixedDY;

            

            model.Elements.Add(e);

            return e.Label;
        }

        private Node nodeExists(TNPoint n)
        {
            if (model.Nodes.Count > 0)
            for (int i=0;i < model.Nodes.Count;i++)
            {
                if ((model.Nodes[i].Location.X == n.X) && (model.Nodes[i].Location.Y == n.Y) && (model.Nodes[i].Location.Z == n.Z)) return model.Nodes[i];
            }
            return null;
        }
        private Constraint restraint(string r)
        {
            Constraint t = new Constraint();
            char a, b, c, d, e, f;
            a = r[0]; b = r[1]; c = r[2]; d = r[3]; e = r[4]; f = r[5];

            if (a.Equals('1')) t = Constraints.FixedDX; else t = Constraints.Released;
            if (b.Equals('1')) t = Constraints.FixedDY; else t = Constraints.Released;
            if (c.Equals('1')) t = Constraints.FixedDZ; else t = Constraints.Released;
            if (d.Equals('1')) t = Constraints.FixedRX; else t = Constraints.Released;
            if (e.Equals('1')) t = Constraints.FixedRY; else t = Constraints.Released;
            if (f.Equals('1')) t = Constraints.FixedRZ; else t = Constraints.Released;

            // t = Constraints.Fixed;

            return t;
        }
        
    }

    public class ProfileClass
    {
        private List<Profiles> I_Profiles;
        private List<Profiles> H_Profiles;
        private List<Profiles> NPU_Profiles;

        public List<Profiles> IPE_list
        {
            get { return I_Profiles; }
        }

        public List<Profiles> HEA_list
        {
            get { return H_Profiles; }
        }

        public List<Profiles> NPU_list
        {
            get { return NPU_Profiles; }
        }

        public ProfileClass()
        {
            LoadProfiles();
        }

        public Profiles findProfile(string pname)
        {
            foreach (Profiles a in IPE_list )
            {
                if (a.name == pname)
                {
                    return a;
                }
            }
                return new Profiles();
        }

        private void LoadProfiles()
        {
            string OneLine = "";
            string[] substr;
            string[] LB = File.ReadAllLines("IPE.txt");
            I_Profiles = new List<Profiles>();

            for (int i = 0; i < LB.Length; i++)
            {
                OneLine = LB[i];
                substr = OneLine.Split('@');
                I_Profiles.Add(new Profiles(substr[0], Convert.ToDouble(substr[1]), Convert.ToDouble(substr[2]), Convert.ToDouble(substr[4]), Convert.ToDouble(substr[3]), Convert.ToDouble(substr[7]), Convert.ToDouble(substr[12]), Convert.ToDouble(substr[14]), Convert.ToDouble(substr[6]), Convert.ToDouble(substr[11])));
            }

            H_Profiles = new List<Profiles>();
            string[] HB = File.ReadAllLines("HEA.txt");

            for (int i = 0; i < HB.Length; i++)
            {
                OneLine = HB[i];
                substr = OneLine.Split('@');
                H_Profiles.Add(new Profiles(substr[0], Convert.ToDouble(substr[2]), Convert.ToDouble(substr[3]), Convert.ToDouble(substr[5]), Convert.ToDouble(substr[4]), Convert.ToDouble(substr[1]), Convert.ToDouble(substr[11]), Convert.ToDouble(substr[14]), Convert.ToDouble(substr[7]), Convert.ToDouble(substr[10])));
            }

            NPU_Profiles = new List<Profiles>();
            string[] NB = File.ReadAllLines("NPU.txt");

            for (int i = 0; i < NB.Length; i++)
            {
                OneLine = NB[i];
                substr = OneLine.Split('@');
                NPU_Profiles.Add(new Profiles(substr[0], Convert.ToDouble(substr[1]), Convert.ToDouble(substr[2]), Convert.ToDouble(substr[4]), Convert.ToDouble(substr[3]), Convert.ToDouble(substr[7]), Convert.ToDouble(substr[10]), Convert.ToDouble(substr[13]), Convert.ToDouble(substr[6]), Convert.ToDouble(substr[10])));
            }
        }

    }
}

And the applying loads....part

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BriefFiniteElementNet.Solver;
using BriefFiniteElementNet.Geometry;
using BriefFiniteElementNet.MpcElements;
using BriefFiniteElementNet.Controls;

namespace Portique
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            var s = new BFEclasses();

            var g1 = s.addFrame(new TNPoint(0, 0, 0), new TNPoint(3, 0, 4), "IPE400", "000000", "000000");

            s.setRestraint("1", "111100");
            s.setRestraint("2", "111000");

            s.addLoadtoFrame(g1, "dead", 'Z', 1000);

            s.analyse();
            

            List<TForces> AA = s.getResults(1);

            int j = 0;
            for (int i=0;i < AA.Count;i++)
            {
          
                dataGridView1.Rows.Add();
                dataGridView1.Rows[j].Cells[1].Value = Convert.ToString(AA[i].st);
                dataGridView1.Rows[j].Cells[0].Value = Convert.ToString(AA[i].fno);
                dataGridView1.Rows[j].Cells[2].Value = Convert.ToString(AA[i].fx);
                dataGridView1.Rows[j].Cells[3].Value = Convert.ToString(AA[i].fy);
                dataGridView1.Rows[j].Cells[4].Value = Convert.ToString(AA[i].fz);
                dataGridView1.Rows[j].Cells[5].Value = Convert.ToString(AA[i].mx);
                dataGridView1.Rows[j].Cells[6].Value = Convert.ToString(AA[i].my);
                dataGridView1.Rows[j].Cells[7].Value = Convert.ToString(AA[i].mz);
                j++;
            }

        }
    }
}

I am trying to apply the same sample in your list but getting errors on model.solve..

can you figure out whats wrong?

**Comment by epsi1on** [comment]
Hi,
`Model.Solve` method will raise error and throw exception is some special cases.
Can you please save your final model into a file (`Model.Save()` method) and upload that file if not problem.
There are some data in your code (txt files) which seems have main data.
Does it throw a error with message "Matrix should be positive and definite"?

**Comment by sbabadag** [comment]
Thanks for the fast repy , and i congratulate you working on a great library like this ;
my whole code is in link i try to compare the results with sap2000 but i get wrong results , i coudnt understand whats wrong and should i give a frame type for the elements ? thanks for your help.
selahattin babadag 
civil eng

the code :  https://we.tl/t-Gi7JiSkoAg

**Comment by sbabadag** [comment]
and yes Matrix should be positive and definite"? error is raised in my code result...

**Comment by sbabadag** [comment]
And as an addition , I think the model doesnt have self weih-ght capability, can it be added in the future development process.

**Comment by sbabadag** [comment]
model file ...

https://we.tl/t-rNnrpdB5bl

**Comment by epsi1on** [comment]
> model file ...
> 
> https://we.tl/t-rNnrpdB5bl

You have a ``BarElement`` with partial end releases. Both ends are connected to nodes with only rotations, so the element is unstable itself (it can move in whole in it's length direction which is local X direction). 
At lease in one end you should set `Dx` to fixed, for either `BarElement.StartReleaseCondition` or `BarElement.EndReleaseCondition` in order to make the `BarElement` stable itself.
Also thanks for suggesting to add self weight feature, that would be good in next verson.
Also please note that nuget package is very old and not updated for a while. I'm waiting to achieve a stable version and release next one. So please use source code instead of nuget package at the time.

Thanks

**Comment by epsi1on** [comment]
For not positive definite, please take a look at here:
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/wiki/How-to-fix-NotPosDef-error
